[package]
edition = { workspace = true }
name = "wsm-enclave"
publish.workspace = true
version = "0.1.0"

[[bin]]
name = "wsm-enclave"

[dependencies]
aes-gcm = "0.10.3"
anyhow = { workspace = true }
aws-nitro-enclaves-nsm-api = "0.4.0"
axum = { workspace = true, features = ["json", "macros"] }
axum-macros = { workspace = true }
base64 = { workspace = true }
bdk = { version = "0.29.0", features = ["minimal", "std"] }
ciborium = "0.2.2"
config = { workspace = true, features = ["toml"] }
crypto = { workspace = true, features = ["noise", "ssb"] }
hex = { workspace = true }
mime = "0.3.17"
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_with = { workspace = true, features = ["base64"] }
subprocess = "0.2.9"
tokio = { workspace = true, features = ["rt-multi-thread", "sync"] }
tower = { workspace = true }

# path dependencies
wsm-common = { workspace = true }

http-body-util = "0.1.0"
sha2 = "0.10.8"

[dev-dependencies]
tower = { workspace = true, features = ["util"] }

[lints]
workspace = true
