package bitkey.auth

import kotlinx.datetime.Instant

/**
 * Auth tokens generated by f8e to authorize certain level of access.
 * The tokens are given when authenticating with f8e using an app authentication key.
 *
 * @param accessToken the token that allows access to f8e. The token can expire
 * and requires to be refreshed by re-authenticating using [refreshToken] and a corresponding auth
 * key.
 * @param refreshToken the token that allows to refresh [accessToken].
 * @param accessTokenExpiresAt when the [accessToken] will expire. Nullable to maintain backwards
 * compatibility with auth tokens generated before support for client expiry, or if there are parsing errors
 * with the stored value.
 * @param refreshTokenExpiresAt when the [refreshToken] will expire. Only updated when generating tokens
 * from the auth challenge and not when refreshing tokens, since the server doesn't know at that time
 * when the refresh token was first issued.
 */
data class AccountAuthTokens(
  val accessToken: AccessToken,
  val refreshToken: RefreshToken,
  val accessTokenExpiresAt: Instant?,
  val refreshTokenExpiresAt: Instant? = null,
)
