package bitkey.auth

/**
 * Scope of Auth Token stored in the AuthTokenDao based on the public key
 * used to authenticate with the server.
 */
enum class AuthTokenScope {
  /**
   * Auth tokens generated by the server via either authentication
   * with [AppGlobalAuthPublicKey] or [HwAuthPublicKey].
   */
  Global,

  /**
   * Auth tokens generated by the server via authentication with [AppRecoveryAuthPublicKey]
   * These tokens will have access to less functionality than [Global] tokens.
   */
  Recovery,
}
