#pragma once

#include "stm32u5xx.h"
#include "stm32u5xx_ll_rcc.h"

#define MCU_USART1  USART1
#define MCU_USART2  USART2
#define MCU_USART3  USART3
#define MCU_UART4   UART4
#define MCU_UART5   UART5
#define MCU_LPUART1 LPUART1

#define MCU_USART1_CLOCK_ENABLE()  LL_APB2_GRP1_EnableClock(LL_APB2_GRP1_PERIPH_USART1)
#define MCU_USART2_CLOCK_ENABLE()  LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_USART2)
#define MCU_USART3_CLOCK_ENABLE()  LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_USART3)
#define MCU_UART4_CLOCK_ENABLE()   LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_UART4)
#define MCU_UART5_CLOCK_ENABLE()   LL_APB1_GRP1_EnableClock(LL_APB1_GRP1_PERIPH_UART5)
#define MCU_LPUART1_CLOCK_ENABLE() LL_APB3_GRP1_EnableClock(LL_APB3_GRP1_PERIPH_LPUART1)

#define MCU_USART1_IRQn  USART1_IRQn
#define MCU_USART2_IRQn  USART2_IRQn
#define MCU_USART3_IRQn  USART3_IRQn
#define MCU_UART4_IRQn   UART4_IRQn
#define MCU_UART5_IRQn   UART5_IRQn
#define MCU_LPUART1_IRQn LPUART1_IRQn
