/**
 * @file
 *
 * @brief Language Pack String IDs
 *
 * @{
 */

#pragma once

/**
 * @brief Enumeration of language pack string IDs (tags).
 *
 * @note Values should be explicitly listed as they identify tags in flash.
 */
typedef enum {
  /**
   * @brief Reserved for TLV sentinel. Do not use.
   */
  LANGPACK_ID_RESERVED = 0,

  /**
   * @brief Reserved for unit tests.
   */
  LANGPACK_ID_TEST_STRING = 1,

  /**
   * @defgroup LANGPACK_ABOUT About Screen Strings
   * @{
   */
  LANGPACK_ID_ABOUT_TITLE = 2,
  LANGPACK_ID_ABOUT_FIRMWARE_LABEL = 3,
  LANGPACK_ID_ABOUT_HARDWARE_LABEL = 4,
  LANGPACK_ID_ABOUT_SERIAL_LABEL = 5,
  /** @} */

  /**
   * @defgroup LANGPACK_BRIGHTNESS Brightness Screen Strings
   * @{
   */
  LANGPACK_ID_BRIGHTNESS_TITLE = 6,
  /** @} */

  /**
   * @defgroup LANGPACK_FINGERPRINT_REMOVE Fingerprint Removal Screen Strings
   * @{
   */
  LANGPACK_ID_FINGERPRINT_REMOVE_TITLE = 7,
  LANGPACK_ID_FINGERPRINT_REMOVE_CONFIRM = 8,
  LANGPACK_ID_FINGERPRINT_REMOVE_BACK = 9,
  LANGPACK_ID_FINGERPRINT_REMOVE_REMOVED = 10,
  /** @} */

  /**
   * @defgroup LANGPACK_FINGERPRINT Fingerprint Management Screen Strings
   * @{
   */
  LANGPACK_ID_FINGERPRINT_TITLE = 11,
  LANGPACK_ID_FINGERPRINT_FINISH_TITLE = 12,
  LANGPACK_ID_FINGERPRINT_INTRO = 13,
  LANGPACK_ID_FINGERPRINT_BUTTON = 14,
  LANGPACK_ID_FINGERPRINT_SUCCESS = 15,
  LANGPACK_ID_FINGERPRINT_FINISH = 16,
  LANGPACK_ID_FINGERPRINT_APP_DOWNLOAD = 17,
  LANGPACK_ID_FINGERPRINT_QR = 18,
  /** @} */

  /**
   * @defgroup LANGPACK_SCAN Scan Screen Strings
   * @{
   */
  LANGPACK_ID_SCAN_TITLE = 19,
  LANGPACK_ID_SCAN_TAP = 20,
  LANGPACK_ID_SCAN_SIGN = 21,
  LANGPACK_ID_SCAN_VERIFY = 22,
  LANGPACK_ID_SCAN_CONFIRM = 23,
  /** @} */

  /**
   * @defgroup LANGPACK_FINGERPRINT_MENU Fingerprint Menu Screen Strings
   * @{
   */
  LANGPACK_ID_FINGERPRINT_MENU_ADD = 24,
  /** @} */

  /**
   * @defgroup LANGPACK_REGULATORY Regulatory Screen Strings
   * @{
   */
  LANGPACK_ID_REGULATORY_TITLE = 25,
  LANGPACK_ID_REGULATORY_FCC_ID = 26,
  LANGPACK_ID_REGULATORY_FCC_NOTES_FMT = 27,
  LANGPACK_ID_REGULATORY_NOTE1 = 28,
  LANGPACK_ID_REGULATORY_NOTE2 = 29,
  /** @} */

  /**
   * @defgroup LANGPACK_MONEY_MOVEMENT Money Movement Screen Strings
   * @{
   */
  LANGPACK_ID_MONEY_MOVEMENT_AMOUNT = 30,
  LANGPACK_ID_MONEY_MOVEMENT_FEE = 31,
  LANGPACK_ID_MONEY_MOVEMENT_HOLD = 32,
  LANGPACK_ID_MONEY_MOVEMENT_BTC_SUFFIX = 33,
  LANGPACK_ID_MONEY_MOVEMENT_SCAN_TO_FINISH = 34,
  LANGPACK_ID_MONEY_MOVEMENT_CONFIRMED = 35,
  /** @} */

  /**
   * @defgroup LANGPACK_HOLD_CANCEL Hold Cancel Widget Strings
   * @{
   */
  LANGPACK_ID_HOLD_CANCEL_CANCEL = 36,
  LANGPACK_ID_HOLD_CANCEL_CANCELLED = 37,
  /** @} */

  /**
   * @defgroup LANGPACK_FINGERPRINT_ENROLL Fingerprint Enrollment Strings
   * @{
   */
  LANGPACK_ID_FINGERPRINT_ENROLL_FIRST = 38,
  LANGPACK_ID_FINGERPRINT_ENROLL_ERROR = 39,
  LANGPACK_ID_FINGERPRINT_ENROLL_FAIL = 40,
  LANGPACK_ID_FINGERPRINT_ENROLL_REPEAT = 41,
  /** @} */

  /**
   * @defgroup LANGPACK_MENU Menu Strings
   * @{
   */
  LANGPACK_ID_MENU_BACK = 42,
  LANGPACK_ID_MENU_FINGERPRINTS = 43,
  LANGPACK_ID_MENU_BRIGHTNESS = 44,
  LANGPACK_ID_MENU_ABOUT = 45,
  LANGPACK_ID_MENU_REGULATORY = 46,
  LANGPACK_ID_MENU_LOCK = 47,
  LANGPACK_ID_MENU_OFF = 48,
  LANGPACK_ID_MENU_TOUCH_TEST = 49,
  LANGPACK_ID_MENU_TITLE = 50,
  LANGPACK_ID_MENU_SLEEP_ENABLED = 51,
  LANGPACK_ID_MENU_SLEEP_DISABLED = 52,
  LANGPACK_ID_MENU_RUN_IN = 53,
  LANGPACK_ID_MENU_MONEY_MOVEMENT = 54,
  /** @} */

  /**
   * @defgroup LANGPACK_PRIVILEGED_ACTION Privileged Action Screen Strings
   * @{
   */
  LANGPACK_ID_PRIVILEGED_ACTION_SCAN_TO_FINISH = 55,
  LANGPACK_ID_PRIVILEGED_ACTION_HASH = 56,
  LANGPACK_ID_PRIVILEGED_ACTION_VERSION = 57,
  LANGPACK_ID_PRIVILEGED_ACTION_UNKNOWN_ERROR = 58,
  /** @} */

  /**
   * @defgroup LANGPACK_FINGERPRINT_REMOVE_ACTIONS Fingerprint Removal Action Strings
   * @{
   */
  LANGPACK_ID_FINGERPRINT_REMOVE_ACTION = 59,
  /** @} */

  /**
   * @defgroup LANGPACK_FIRMWARE_UPDATE Firmware Update Screen Strings
   * @{
   */
  LANGPACK_ID_FIRMWARE_UPDATE_VERIFY = 60,
  LANGPACK_ID_FIRMWARE_UPDATE_CANCEL = 61,
  LANGPACK_ID_FIRMWARE_UPDATE_IN_PROGRESS = 62,
  LANGPACK_ID_FIRMWARE_UPDATE_HASH_TITLE = 63,
  LANGPACK_ID_FIRMWARE_UPDATE_FINISH_TITLE = 64,
  LANGPACK_ID_FIRMWARE_UPDATE_UPDATING_TITLE = 65,
  /** @} */

  /**
   * @defgroup LANGPACK_FINGERPRINT_MENU_TITLE Fingerprint Menu Title
   * @{
   */
  LANGPACK_ID_FINGERPRINT_MENU_TITLE = 66,
  /** @} */

  /**
   * @defgroup LANGPACK_FIRMWARE_UPDATE_CONFIRMATION Firmware Update Confirmation Strings
   * @{
   */
  LANGPACK_ID_FIRMWARE_UPDATE_TITLE = 67,
  LANGPACK_ID_FIRMWARE_UPDATE_MCU_CORE = 68,
  LANGPACK_ID_FIRMWARE_UPDATE_MCU_UXC = 69,
  /** @} */
} langpack_string_id_t;

/** @} */
