[package]
edition = { workspace = true }
name = "s3-utils"
publish = { workspace = true }
version = "0.1.0"

[dependencies]
aws-config = { workspace = true }
aws-sdk-s3 = "1.17.0"
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
rstest = { workspace = true }

[features]
test-helpers = []

[lints]
workspace = true
