#pragma once

#include "attributes.h"
#include "auth_task.h"
#include "bio.h"
#include "bitlog.h"
#include "board_id.h"
#include "canary.h"
#include "captouch_task.h"
#include "clock.h"
#include "filesystem.h"
#include "fwup_task.h"
#include "key_manager_task.h"
#include "led.h"
#include "led_task.h"
#include "mcu_i2c.h"
#include "mcu_smu.h"
#include "mcu_wdog.h"
#include "memfault.h"
#include "mfgtest_task.h"
#include "mpu_regions.h"
#include "nfc_task.h"
#include "platform.h"
#include "power.h"
#include "printf.h"
#include "rtos.h"
#include "secure_channel.h"
#include "secure_engine.h"
#include "secure_rng.h"
#include "secutils.h"
#include "serial.h"
#ifndef CONFIG_PROD
#include "shell_task.h"
#endif
#include "sysevent.h"
#include "sysinfo.h"
#include "sysinfo_task.h"
#include "tamper.h"
#include "task.h"
#include "telemetry_storage.h"

#include "em_chip.h"

#include <stdbool.h>
