[package]
edition = { workspace = true }
name = "mobile_pay"
publish = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
axum = { workspace = true }
axum-macros = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_with = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }

# path dependencies
account = { workspace = true }
authn_authz = { workspace = true }
bdk_utils = { workspace = true }
database = { workspace = true }
errors = { workspace = true }
exchange_rate = { workspace = true }
experimentation = { workspace = true }
feature_flags = { workspace = true }
http_server = { workspace = true }
instrumentation = { workspace = true }
migration = { workspace = true }
screener = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true }
transaction_verification = { workspace = true }
types = { workspace = true, features = [
  "currencies",
  "exchange_rate",
  "serde",
] }
userpool = { workspace = true }
wsm-grant = { workspace = true }
wsm-rust-client = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }
rstest = { workspace = true }
wsm-common = { workspace = true }

[lints]
workspace = true
