[package]
edition = { workspace = true }
name = "secure_site"
publish = { workspace = true }
version = "0.1.0"

[dependencies]
axum = { workspace = true }
mime_guess = "2.0.5"
regex = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
