steps:
  - label: "PR Unit Tests"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
        - exit_status: 255 # Forced agent shutdown
          limit: 2
    agents:
      xcode: 16.2.0
      ios: 18.3.1
    plugins:
      - squareup/ios-builder#v1.0.0:
          build_action: unit
  - label: "PR Snapshot Tests"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
        - exit_status: 255 # Forced agent shutdown
          limit: 2
    agents:
      xcode: 16.2.0
      ios: 18.3.1
    plugins:
      - squareup/ios-builder#v1.0.0:
          build_action: ios-snapshots
  - label: "PR KMP iOS Test"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
        - exit_status: 255 # Forced agent shutdown
          limit: 2
    agents:
      xcode: 16.2.0
    plugins:
      - squareup/macos-environment:
          xcode_version: 16.2.0
    command:
      - "./app/ios/Scripts/CI/RunKmpIosTests"