notify:
  - slack: "#bitkey-mobile-robots"
    if: build.state == "failed"

steps:
  - label: "Main branch debug build"
    agents:
      xcode: 16.2.0
      ios: 18.3.1
    plugins:
      - squareup/ios-builder#v1.0.0:
          build_action: debug
  - label: "Main branch unit test"
    agents:
      xcode: 16.2.0
      ios: 18.3.1
    plugins:
      - squareup/ios-builder#v1.0.0:
          build_action: unit