steps:
  - label: "PR Unit Tests"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
        - exit_status: 255 # Forced agent shutdown
          limit: 2
    agents:
      xcode: 26.2.0
    env:
      SKIP_BUILDKITE_AGENT_CHECKOUT: "true"
    plugins:
      - squareup/ios-builder#v1.1.3:
          build_action: unit
  - label: "PR Snapshot Tests"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
        - exit_status: 255 # Forced agent shutdown
          limit: 2
    agents:
      xcode: 26.2.0
    env:
      SKIP_BUILDKITE_AGENT_CHECKOUT: "true"
    plugins:
      - squareup/ios-builder#v1.1.3:
          build_action: ios-snapshots
  - label: "PR KMP iOS Test"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
        - exit_status: 255 # Forced agent shutdown
          limit: 2
    agents:
      xcode: 26.2.0
    plugins:
      - squareup/macos-environment:
          xcode_version: 26.2.0
    command:
      - "./app/ios/Scripts/CI/RunKmpIosTests"
