notify:
  - slack: "#bitkey-releases"
    if: build.state == "failed"

steps:
  - label: "Release build"
    retry:
      automatic:
        - exit_status: -1  # Agent was lost
          limit: 2
        - exit_status: 255 # Forced agent shutdown
          limit: 2
    agents:
      xcode: 26.2.0
    env:
      SKIP_BUILDKITE_AGENT_CHECKOUT: "true"
    plugins:
      - squareup/ios-builder#v1.0.0:
          build_action: release
          options: --manual-mpp
