FROM rust:1.86.0-alpine@sha256:661d708cc863ce32007cf46807a72062a80d2944a6fae9e0d83742d2e04d5375 AS build
RUN apk update && apk add --no-cache openssl-dev musl-dev make automake protoc git
RUN rustup update
WORKDIR /usr/src/lambdas
COPY --from=core . ../core
COPY . .
RUN cd src/api/partnerships/partnerships_lib/src/partners/cash_app/lambdas && cargo install --locked --bin key_rotator --path .

FROM alpine:3.21.0@sha256:21dc6063fd678b478f57c0e13f47560d0ea4eeba26dfc947b2a4f81f686b9f45 AS deployable
COPY --from=build /usr/local/cargo/bin/key_rotator /var/task/bootstrap
CMD [ "/var/task/bootstrap" ]
