FROM rust:1.82.0-alpine@sha256:2f42ce0d00c0b14f7fd84453cdc93ff5efec5da7ce03ead6e0b41adb1fbe834e AS build
RUN apk update && apk add --no-cache openssl-dev musl-dev make automake protoc git
RUN rustup update
WORKDIR /usr/src/lambdas
COPY --from=core . ../core
COPY . .
RUN cd src/api/partnerships/partnerships_lib/src/partners/cash_app/lambdas && cargo install --locked --bin key_rotator --path .

FROM alpine:3.21.0@sha256:21dc6063fd678b478f57c0e13f47560d0ea4eeba26dfc947b2a4f81f686b9f45 AS deployable
COPY --from=build /usr/local/cargo/bin/key_rotator /var/task/bootstrap
CMD [ "/var/task/bootstrap" ]
