#pragma once

// Autogenerated - do not modify

{% for header in headers -%}
#include "{{header}}"
{% endfor %}
{% for port in ports -%}
extern const uint32_t {{port}};
{% endfor %}

{% for port, protos in port_to_proto.items() %}
typedef union {
{% for proto in protos %}
  {{proto}} {{proto}};
{% endfor %}
} {{port}}_cmd_union_t;

#define MAX_{{port.upper()}}_CMD_SIZE (sizeof({{port}}_cmd_union_t))

{% endfor %}
