#include "assert.h"
#include "auth.h"
#include "ipc_impl.h"
#include "log.h"
#include "onboarding.h"
#include "pb_decode.h"
#include "pb_encode.h"
#include "secutils.h"
#include "sleep.h"
#include "wallet.pb.h"

#include <stdint.h>
#include <string.h>

// Autogenerated - do not modify

// clang-format off
SHARED_TASK_BSS ipc_port_obj_t ports[{{num_ports}}] __attribute__((__used__)) = {0};
SHARED_TASK_DATA uint32_t num_ipc_ports = {{num_ports}};


{% for port in ports -%}
const uint32_t {{port}} = {{loop.index - 1}};
{% endfor %}

static bool send_unknown_rsp(uint32_t seq) {
  fwpb_wallet_rsp* rsp = (fwpb_wallet_rsp*)ipc_proto_alloc(sizeof(fwpb_wallet_rsp));
  memset(rsp, 0, sizeof(fwpb_wallet_rsp));

  rsp->status = fwpb_status_UNKNOWN_MESSAGE;
  rsp->unknown_msg = true;

  uint8_t* buffer = ipc_proto_get_response_buffer();
  ipc_proto_set_response_seq(seq);
  pb_ostream_t ostream = pb_ostream_from_buffer(buffer, fwpb_wallet_rsp_size);

  pb_encode(&ostream, fwpb_wallet_rsp_fields, rsp);
  ipc_proto_send_response_buffer(buffer, ostream.bytes_written);
  ipc_proto_free((uint8_t*)rsp);

  return true;
}

NO_OPTIMIZE secure_bool_t check_authentication(uint16_t pb_tag, uint32_t seq) {
  secure_glitch_random_delay();

  // Check if the message does NOT require authentication.
  switch (pb_tag) {
    {% for proto in protos_that_never_require_auth %}
    case fwpb_wallet_cmd_{{'_'.join(proto.split('_')[1:])}}_tag:
    {% endfor %}
#ifndef CONFIG_PROD
    {% for proto in protos_that_are_only_present_in_dev %}
    case fwpb_wallet_cmd_{{'_'.join(proto.split('_')[1:])}}_tag:
    {% endfor %}
#endif
      // No auth required, so return SECURE_TRUE here to indicate that
      // the auth status is okay.
      return SECURE_TRUE;
    default:
      break;
  }

  // Check if the message requires authentication only on an onboarded wallet.
  switch (pb_tag) {
    {% for proto in protos_that_require_auth_after_onboarding %}
    case fwpb_wallet_cmd_{{'_'.join(proto.split('_')[1:])}}_tag:
    {% endfor %}
    {
      volatile secure_bool_t onboarding_completed = onboarding_complete();
      SECURE_DO_FAILOUT(onboarding_completed == SECURE_FALSE, {
        // Not onboarded. Same as above, return SECURE_TRUE to indicate that
        // authentication is not required.
        return SECURE_TRUE;
      });
      // Onboarded: break out to the auth check.
      break;
    }
    default:
      break;
  }

  // Check if the message requires device to NOT be onboarded (factory/packout only).
  switch (pb_tag) {
    {% for proto in protos_that_require_not_onboarded %}
    case fwpb_wallet_cmd_{{'_'.join(proto.split('_')[1:])}}_tag:
    {% endfor %}
    {
      volatile secure_bool_t onboarding_completed = onboarding_complete();
      SECURE_DO_FAILIN(onboarding_completed != SECURE_FALSE, {
        // Device is onboarded or in an invalid state - command not allowed.
        // Send error response before returning.
        fwpb_wallet_rsp* rsp = (fwpb_wallet_rsp*)ipc_proto_alloc(sizeof(fwpb_wallet_rsp));
        memset(rsp, 0, sizeof(fwpb_wallet_rsp));

        rsp->which_msg = pb_tag;
        rsp->status = fwpb_status_UNAUTHENTICATED;

        uint8_t* buffer = ipc_proto_get_response_buffer();
        ipc_proto_set_response_seq(seq);
        pb_ostream_t ostream = pb_ostream_from_buffer(buffer, fwpb_wallet_rsp_size);

        pb_encode(&ostream, fwpb_wallet_rsp_fields, rsp);
        ipc_proto_send_response_buffer(buffer, ostream.bytes_written);
        ipc_proto_free((uint8_t*)rsp);

        return SECURE_FALSE;
      });
      // Not onboarded: allow without authentication.
      return SECURE_TRUE;
    }
    default:
      break;
  }

  // Grant logic follows.
  SECURE_DO_FAILOUT(is_allowing_fingerprint_enrollment() == SECURE_TRUE, {
    switch (pb_tag) {
      case fwpb_wallet_cmd_start_fingerprint_enrollment_cmd_tag:
        return SECURE_TRUE;
      case fwpb_wallet_cmd_delete_fingerprint_cmd_tag:
        return SECURE_TRUE;
      default:
        break;
    }
  });

  // Authentication logic follows.

  fwpb_wallet_rsp* rsp = (fwpb_wallet_rsp*)ipc_proto_alloc(sizeof(fwpb_wallet_rsp));
  memset(rsp, 0, sizeof(fwpb_wallet_rsp));

  rsp->which_msg = pb_tag;
  rsp->status = fwpb_status_UNSPECIFIED;

  volatile secure_bool_t auth_ok = SECURE_FALSE;
  auth_ok = is_authenticated();

  SECURE_DO_FAILIN(auth_ok != SECURE_TRUE, {
    rsp->status = fwpb_status_UNAUTHENTICATED;
    uint8_t* buffer = ipc_proto_get_response_buffer();
    ipc_proto_set_response_seq(seq);
    pb_ostream_t ostream = pb_ostream_from_buffer(buffer, fwpb_wallet_rsp_size);

    pb_encode(&ostream, fwpb_wallet_rsp_fields, rsp);
    ipc_proto_send_response_buffer(buffer, ostream.bytes_written);
    ipc_proto_free((uint8_t*)rsp);
    return SECURE_FALSE;
  });

  ipc_proto_free((uint8_t*)rsp);
  return SECURE_TRUE;
}

static bool route_proto_cmd(ipc_port_t port, uint32_t tag, uint8_t* buffer, uint32_t size,
                            uint32_t seq) {
  const size_t routed_size = sizeof(ipc_proto_routed_cmd_t) + size;
  ipc_proto_routed_cmd_t* routed_cmd = (ipc_proto_routed_cmd_t*)ipc_proto_alloc(routed_size);
  if (routed_cmd == NULL) {
    return false;
  }

  routed_cmd->seq = seq;
  memcpy(routed_cmd->encoded_cmd, buffer, size);

  if (!ipc_send(port, routed_cmd, routed_size, tag)) {
    ipc_proto_free((uint8_t*)routed_cmd);
    return false;
  }

  return true;
}

NO_OPTIMIZE bool ipc_proto_route(uint16_t pb_tag, uint8_t* buffer, uint32_t size, uint32_t seq) {
  sleep_refresh_power_timer();

  volatile secure_bool_t auth_ok = check_authentication(pb_tag, seq);
  SECURE_IF_FAILIN(auth_ok != SECURE_TRUE) {
    LOGW("Unauthenticated");
    return true;
  };

  refresh_auth();

  switch (pb_tag) {
    {% for port, protos in port_to_proto.items() %}
    {% for proto in protos %}
    case fwpb_wallet_cmd_{{'_'.join(proto.split('_')[1:])}}_tag: {
      return route_proto_cmd({{port}}, IPC_PROTO_{{'_'.join(proto.upper().split('_')[1:])}}, buffer, size, seq);
    }
    {% endfor %}

    {% endfor %}
    default:
      LOGE("Got unknown proto with tag %d\n", pb_tag);
      return send_unknown_rsp(seq);
  }
}

      // clang-format on
