import core
import Foundation
import Shared

public final class P256BoxImpl: Shared.P256Box {
    public init() {}

    public func generateKeyPair() -> Shared.P256BoxKeyPair {
        let keyPair = core.P256BoxKeyPair()
        let publicKey = P256BoxPublicKey(bytes: OkioKt.ByteString(data: keyPair.publicKey()))
        let privateKey = P256BoxPrivateKey(bytes: OkioKt.ByteString(data: keyPair.secretKey()))

        return P256BoxKeyPair(privateKey: privateKey, publicKey: publicKey)
    }

    public func keypairFromSecretBytes(secretBytes: OkioByteString) throws -> Shared
        .P256BoxKeyPair
    {
        let keyPair = try core.P256BoxKeyPair.fromSecretBytes(secretBytes: secretBytes.toData())
        let publicKey = P256BoxPublicKey(bytes: OkioKt.ByteString(data: keyPair.publicKey()))
        let privateKey = P256BoxPrivateKey(bytes: OkioKt.ByteString(data: keyPair.secretKey()))

        return P256BoxKeyPair(privateKey: privateKey, publicKey: publicKey)
    }

    public func decrypt(
        theirPublicKey: P256BoxPublicKey,
        myPrivateKey: P256BoxPrivateKey,
        // Autogenerated Shared.P256Box appends underscore to avoid conflict with Shared.CryptoBox
        // function
        sealedData_ sealedData: XCiphertext
    ) throws -> OkioByteString {
        let p256Box = try core.P256Box(
            publicKey: theirPublicKey.bytes.toData(),
            secretKey: myPrivateKey.bytes.toData()
        )
        let xSealedData = try sealedData.toXSealedData()
        let plaintext = try p256Box.decrypt(
            nonce: xSealedData.nonce.bytes.toData(),
            ciphertext: xSealedData.ciphertext.toData()
        )

        return OkioKt.ByteString(data: plaintext)
    }

    public func encrypt(
        theirPublicKey: P256BoxPublicKey,
        myPrivateKey: P256BoxPrivateKey,
        nonce: XNonce,
        // Autogenerated Shared.P256Box appends underscore to avoid conflict with Shared.CryptoBox
        // function
        plaintext_ plaintext: OkioByteString
    ) throws -> XCiphertext {
        let p256Box = try core.P256Box(
            publicKey: theirPublicKey.bytes.toData(),
            secretKey: myPrivateKey.bytes.toData()
        )
        let ciphertext = try p256Box.encrypt(
            nonce: nonce.bytes.toData(),
            plaintext: plaintext.toData()
        )

        return XSealedData(
            header: XSealedData.Header(format: .standard, algorithm: P256BoxCompanion().ALGORITHM),
            ciphertext: OkioKt.ByteString(data: ciphertext),
            nonce: nonce,
            publicKey: nil
        ).toOpaqueCiphertext()
    }
}
