#!/bin/bash

# Hack from https://gitlab.com/fdroid/fdroidserver/-/blob/master/buildserver/provision-android-sdk#L99 to accept SDK license
# Using `yes | sdkmanager --licenses` proved to be unreliable due to request throttling done by Gitlab

mkdir -p "$ANDROID_HOME"/licenses/

cat << EOF > "$ANDROID_HOME"/licenses/android-sdk-license
8933bad161af4178b1185d1a37fbf41ea5269c55
d56f5187479451eabf01fb78af6dfcb131a6481e
24333f8a63b6825ea9c5514f83c2829b004d1fee
EOF
