#!/bin/bash

# Normalizes APKs names by replacing them by numbers derived by sorting the directories by their content size.
# This step is necessary due to locally built APKs having a slightly different names compared to the downloaded APKs which would break their comparison.
# The script does not modify the input directory and instead puts the result into the output directory.

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <input-directory> <output-directory>" >&2
    exit 1
fi

if [ -e "$2" ]; then
  echo "Provided output directory '$2' already exists. Please delete it before running the script again." >&2
  exit 2
fi

if ! which "du" > /dev/null 2>&1; then
    echo "Cannot find 'du'. Please install it first and then rerun this command." >&2
    exit 100
fi

mkdir -p "$2"

sorted_directories=$(find "$1" -maxdepth 1 -mindepth 1 -type d -exec du -s {} \; | sort -nr | cut -f 2)

i=0

for directory in $sorted_directories; do
    mkdir "$2/$i"

    cp -r "$directory/" $"$2/$i"

    ((i++))
done
