[package]
edition = { workspace = true }
name = "experimentation"
publish = { workspace = true }
version = "0.1.0"

[dependencies]
axum = { workspace = true }
axum-macros = { workspace = true }
http_server = { workspace = true }
once_cell = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
utoipa = { workspace = true }

# path dependencies
account = { workspace = true }
authn_authz = { workspace = true }
errors = { workspace = true }
feature_flags = { workspace = true }
instrumentation = { workspace = true }
types = { workspace = true, features = ["account"] }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
