[default]
address = "0.0.0.0"
dynamodb = { test = false }
launchdarkly = "environment"
use_local_wallet_id = false
override_current_time = false
int_secure_site_base_url = "http://localhost:8080"
ext_secure_site_base_url = "http://localhost:8080"
wsm_endpoint = "https://wsm-main.dev.wallet.build"
wallet_telemetry = { service_name = "fromagerie" }
use_local_currency_exchange = false
cognito = "test"
analytics_destination = "Stdout"
analytics_api_url = ""
sqs = "test"
ses = "test"
iterable = { mode = "test" }
sns = "test"
twilio = { mode = "test" }
webhook = { mode = "test" }
web_shop = { mode = "test" }
zendesk = { mode = "test" }
screener = { mode = "test" }
linear = "test"
allow_test_accounts_with_mainnet_keysets = true
known_fields.18558334323604 = "Country"
known_fields.17171619135892 = "HardwareSerialNumber"
known_fields.17171594621332 = "PhoneMakeAndModel"
known_fields.19386550194836 = "SystemNameAndVersion"
known_fields.19386560407956 = "AppVersion"
known_fields.19386627184148 = "HardwareFirmwareVersion"
monitored_electrum_nodes = []
kms = "test"
encrypted_attachment_kms_key_id = "fake-encrypted-attachment-kms-key-id"

[test-docker]
port = 8080
dynamodb = { endpoint = "http://dynamodb:8000" }
wsm_endpoint = "http://wsm-api:9090"
wallet_telemetry = { mode = "jaeger" }
use_local_currency_exchange = true
use_local_sns = true
sql = "test"

[debug]
port = 8080
dynamodb = { endpoint = "http://localhost:8000" }
sql = { endpoint = "mysql://localhost/api-debug" }
use_local_sns = true
wsm_endpoint = "http://localhost:9090"
wallet_telemetry = { mode = "jaeger" }
cognito = "test"
sqs = "test"

[test]
port = 8080
dynamodb = "test"
# LaunchDarkly is not available in unit tests. Any flags that need to be evaluated in tests
# should be added to src/feature_flags/overrides/test.toml
launchdarkly = "test"
feature_flag_overrides = { file = "test" }
sql = "test"
use_local_sns = true
use_local_wallet_id = true
override_current_time = true
use_local_currency_exchange = true
wsm_endpoint = "http://localhost:9090"
cognito = "test"
sqs = "test"
allow_test_accounts_with_mainnet_keysets = false

[localprod]
port = 8080
dynamodb = "test"
sql = { endpoint = "mysql://host.docker.internal/api" }
use_local_sns = true
wallet_telemetry = { mode = "jaeger" }
cognito = "test"
wsm_endpoint = "http://localhost:9090"
sqs = "test"

[development]
port = 80
dynamodb = "environment"
sql = "environment"
use_local_sns = false
wsm_endpoint = "https://wsm-main.dev.wallet.build"
wallet_telemetry = { mode = "datadog" }
cognito = "environment"
sqs = "environment"
ses = "environment"
sns = "environment"
linear = "environment"
analytics_destination = "Segment"
analytics_api_url = "https://api.segment.io"
# Iterable
iterable.mode = "environment"
iterable.comms_verification_campaign_id = 9281957
iterable.privileged_action_canceled_out_of_band_verification_campaign_id = 13993615
iterable.privileged_action_completed_out_of_band_verification_campaign_id = 13993614
iterable.privileged_action_pending_out_of_band_verification_campaign_id = 13993611
iterable.recovery_pending_delay_period_lost_app_campaign_id = 9234980
iterable.recovery_pending_delay_period_lost_hw_campaign_id = 9234864
iterable.recovery_completed_delay_period_lost_app_campaign_id = 9235008
iterable.recovery_completed_delay_period_lost_hw_campaign_id = 9234993
iterable.recovery_canceled_delay_period_lost_app_campaign_id = 9235101
iterable.recovery_canceled_delay_period_lost_hw_campaign_id = 9235091
iterable.recovery_relationship_invitation_accepted_received_by_protected_customer_campaign_id = 9235205
iterable.recovery_relationship_invitation_accepted_received_by_benefactor_campaign_id = 12397826
iterable.recovery_relationship_invitation_accepted_received_by_beneficiary_campaign_id = 12398592
iterable.recovery_relationship_deleted_campaign_id = 9235258
iterable.recovery_relationship_invitation_deleted_by_benefactor_received_by_benefactor_campaign_id = 12397867
iterable.recovery_relationship_invitation_deleted_by_benefactor_received_by_beneficiary_campaign_id = 12397835
iterable.recovery_relationship_invitation_deleted_by_beneficiary_received_by_benefactor_campaign_id = 12397862
iterable.recovery_relationship_invitation_deleted_by_beneficiary_received_by_beneficiary_campaign_id = 12397848
iterable.social_challenge_response_received_campaign_id = 9235231
iterable.inheritance_claim_almost_over_as_benefactor_campaign_id = 12396525
iterable.inheritance_claim_almost_over_as_beneficiary_campaign_id = 12397794
iterable.inheritance_claim_canceled_by_beneficiary_received_by_beneficiary_campaign_id = 12396008
iterable.inheritance_claim_canceled_by_benefactor_received_by_beneficiary_campaign_id = 12398066
iterable.inheritance_claim_initiated_as_benefactor_campaign_id = 12395334
iterable.inheritance_claim_initiated_as_beneficiary_campaign_id = 12395410
iterable.inheritance_claim_canceled_by_benefactor_received_by_benefactor_campaign_id = 12396522
iterable.inheritance_claim_canceled_by_beneficiary_received_by_benefactor_campaign_id = 12396503
iterable.inheritance_claim_period_completed_by_benefactor_campaign_id = 12398488
iterable.inheritance_claim_period_completed_by_beneficiary_campaign_id = 12398490
iterable.marketing_channel_id = 87983
iterable.transactional_channel_id = 87984
iterable.account_security_message_type_id = 125365
iterable.money_movement_message_type_id = 125366
iterable.product_marketing_message_type_id = 125367
iterable.recovery_relationship_benefactor_invitation_pending_campaign_id = 12397809
iterable.transaction_verification_campaign_id = 13512543
iterable.security_hub_campaign_id = 13770103
# Twilio
twilio.mode = "environment"
twilio.default_messaging_service_sid = "MGc5bcad97fd996a1a6db5d010a34ff55c"
# Web Shop
web_shop.mode = "environment"
web_shop.base_url = "https://web-shop-api.bitkeystaging.com"
# Webhook
webhook.mode = "environment"
screener = { mode = "s3" }
monitored_electrum_nodes = [
    { network = "bitcoin", provider = "mempool", uri = "ssl://bitkey.va1.mempool.space:50002" },
    { network = "bitcoin", provider = "mempool", uri = "ssl://bitkey.fra.mempool.space:50002" },
    { network = "bitcoin", provider = "mempool", uri = "ssl://bitkey.tk7.mempool.space:50002" },
    { network = "bitcoin", provider = "blockstream", uri = "tcp://35.192.20.52:50001" },
    { network = "bitcoin", provider = "blockstream", uri = "tcp://34.147.244.49:50001" },
    { network = "bitcoin", provider = "blockstream", uri = "tcp://34.131.144.107:50001" },
]
kms = "environment"

[staging]
port = 80
dynamodb = "environment"
sql = "environment"
use_local_sns = false
int_secure_site_base_url = "https://secure.bitkeystaging.com"
ext_secure_site_base_url = "https://secure.bitkeystaging.world"
wsm_endpoint = "https://wsm-main.dev.wallet.build"
wallet_telemetry = { mode = "datadog" }
cognito = "environment"
sqs = "environment"
ses = "environment"
sns = "environment"
linear = "environment"
analytics_destination = "Segment"
analytics_api_url = "https://api.segment.io"
# Iterable
iterable.mode = "environment"
iterable.comms_verification_campaign_id = 9281957
iterable.privileged_action_canceled_out_of_band_verification_campaign_id = 13993615
iterable.privileged_action_completed_out_of_band_verification_campaign_id = 13993614
iterable.privileged_action_pending_out_of_band_verification_campaign_id = 13993611
iterable.recovery_pending_delay_period_lost_app_campaign_id = 9234980
iterable.recovery_pending_delay_period_lost_hw_campaign_id = 9234864
iterable.recovery_completed_delay_period_lost_app_campaign_id = 9235008
iterable.recovery_completed_delay_period_lost_hw_campaign_id = 9234993
iterable.recovery_canceled_delay_period_lost_app_campaign_id = 9235101
iterable.recovery_canceled_delay_period_lost_hw_campaign_id = 9235091
iterable.recovery_relationship_invitation_accepted_received_by_protected_customer_campaign_id = 9235205
iterable.recovery_relationship_invitation_accepted_received_by_benefactor_campaign_id = 12397826
iterable.recovery_relationship_invitation_accepted_received_by_beneficiary_campaign_id = 12398592
iterable.recovery_relationship_deleted_campaign_id = 9235258
iterable.recovery_relationship_invitation_deleted_by_benefactor_received_by_benefactor_campaign_id = 12397867
iterable.recovery_relationship_invitation_deleted_by_benefactor_received_by_beneficiary_campaign_id = 12397835
iterable.recovery_relationship_invitation_deleted_by_beneficiary_received_by_benefactor_campaign_id = 12397862
iterable.recovery_relationship_invitation_deleted_by_beneficiary_received_by_beneficiary_campaign_id = 12397848
iterable.social_challenge_response_received_campaign_id = 9235231
iterable.inheritance_claim_almost_over_as_benefactor_campaign_id = 12396525
iterable.inheritance_claim_almost_over_as_beneficiary_campaign_id = 12397794
iterable.inheritance_claim_canceled_by_beneficiary_received_by_beneficiary_campaign_id = 12396008
iterable.inheritance_claim_canceled_by_benefactor_received_by_beneficiary_campaign_id = 12398066
iterable.inheritance_claim_initiated_as_benefactor_campaign_id = 12395334
iterable.inheritance_claim_initiated_as_beneficiary_campaign_id = 12395410
iterable.inheritance_claim_canceled_by_benefactor_received_by_benefactor_campaign_id = 12396522
iterable.inheritance_claim_canceled_by_beneficiary_received_by_benefactor_campaign_id = 12396503
iterable.inheritance_claim_period_completed_by_benefactor_campaign_id = 12398488
iterable.inheritance_claim_period_completed_by_beneficiary_campaign_id = 12398490
iterable.marketing_channel_id = 87983
iterable.transactional_channel_id = 87984
iterable.account_security_message_type_id = 125365
iterable.money_movement_message_type_id = 125366
iterable.product_marketing_message_type_id = 125367
iterable.recovery_relationship_benefactor_invitation_pending_campaign_id = 12397809
iterable.transaction_verification_campaign_id = 13512543
iterable.security_hub_campaign_id = 13770103
# Twilio
twilio.mode = "environment"
twilio.default_messaging_service_sid = "MGc5bcad97fd996a1a6db5d010a34ff55c"
# Web Shop
web_shop.mode = "environment"
web_shop.base_url = "https://web-shop-api.bitkeystaging.com"
# Webhook
webhook.mode = "environment"
zendesk = { mode = "environment" }
screener = { mode = "s3" }
monitored_electrum_nodes = [
    { network = "bitcoin", provider = "mempool", uri = "ssl://bitkey.va1.mempool.space:50002" },
    { network = "bitcoin", provider = "mempool", uri = "ssl://bitkey.fra.mempool.space:50002" },
    { network = "bitcoin", provider = "mempool", uri = "ssl://bitkey.tk7.mempool.space:50002" },
    { network = "bitcoin", provider = "blockstream", uri = "tcp://35.192.20.52:50001" },
    { network = "bitcoin", provider = "blockstream", uri = "tcp://34.147.244.49:50001" },
    { network = "bitcoin", provider = "blockstream", uri = "tcp://34.131.144.107:50001" },
]
kms = "environment"

[production]
port = 80
dynamodb = "environment"
sql = "environment"
use_local_sns = false
int_secure_site_base_url = "https://secure.bitkeyproduction.com"
ext_secure_site_base_url = "https://secure.bitkey.world"
wsm_endpoint = "https://wsm-main.dev.wallet.build"
wallet_telemetry = { mode = "datadog" }
cognito = "environment"
sqs = "environment"
ses = "environment"
sns = "environment"
linear = "environment"
analytics_destination = "Segment"
analytics_api_url = "https://api.segment.io"
# Iterable
iterable.mode = "environment"
iterable.comms_verification_campaign_id = 9282843
iterable.privileged_action_canceled_out_of_band_verification_campaign_id = 13993609
iterable.privileged_action_completed_out_of_band_verification_campaign_id = 13993605
iterable.privileged_action_pending_out_of_band_verification_campaign_id = 13993591
iterable.recovery_pending_delay_period_lost_app_campaign_id = 9284325
iterable.recovery_pending_delay_period_lost_hw_campaign_id = 9284300
iterable.recovery_completed_delay_period_lost_app_campaign_id = 9284352
iterable.recovery_completed_delay_period_lost_hw_campaign_id = 9284334
iterable.recovery_canceled_delay_period_lost_app_campaign_id = 9284409
iterable.recovery_canceled_delay_period_lost_hw_campaign_id = 9284374
iterable.recovery_relationship_invitation_accepted_received_by_protected_customer_campaign_id = 9284438
iterable.recovery_relationship_invitation_accepted_received_by_benefactor_campaign_id = 12609258
iterable.recovery_relationship_invitation_accepted_received_by_beneficiary_campaign_id = 11696296
iterable.recovery_relationship_deleted_campaign_id = 9284488
iterable.recovery_relationship_invitation_deleted_by_benefactor_received_by_benefactor_campaign_id = 11705234
iterable.recovery_relationship_invitation_deleted_by_benefactor_received_by_beneficiary_campaign_id = 11698700
iterable.recovery_relationship_invitation_deleted_by_beneficiary_received_by_benefactor_campaign_id = 12610834
iterable.recovery_relationship_invitation_deleted_by_beneficiary_received_by_beneficiary_campaign_id = 11698724
iterable.social_challenge_response_received_campaign_id = 9284476
iterable.inheritance_claim_almost_over_as_benefactor_campaign_id = 12611107
iterable.inheritance_claim_almost_over_as_beneficiary_campaign_id = 11713212
iterable.inheritance_claim_canceled_by_beneficiary_received_by_beneficiary_campaign_id = 11621282
iterable.inheritance_claim_canceled_by_benefactor_received_by_beneficiary_campaign_id = 11622149
iterable.inheritance_claim_canceled_by_benefactor_received_by_benefactor_campaign_id = 12611330
iterable.inheritance_claim_canceled_by_beneficiary_received_by_benefactor_campaign_id = 12611373
iterable.inheritance_claim_initiated_as_benefactor_campaign_id = 12611054
iterable.inheritance_claim_initiated_as_beneficiary_campaign_id = 11620686
iterable.inheritance_claim_period_completed_by_benefactor_campaign_id = 11622214
iterable.inheritance_claim_period_completed_by_beneficiary_campaign_id = 12611285
iterable.marketing_channel_id = 87980
iterable.transactional_channel_id = 87981
iterable.account_security_message_type_id = 125506
iterable.money_movement_message_type_id = 125507
iterable.product_marketing_message_type_id = 125505
iterable.recovery_relationship_benefactor_invitation_pending_campaign_id = 12610561
iterable.transaction_verification_campaign_id = 13509717
iterable.security_hub_campaign_id = 13769914
# Twilio
twilio.mode = "environment"
twilio.default_messaging_service_sid = "MGc5bcad97fd996a1a6db5d010a34ff55c"
twilio.status_callback_override = "https://api.bitkey.world/api/twilio/status-callback"
# Web Shop
web_shop.mode = "environment"
web_shop.base_url = "https://web-shop-api.bitkeyproduction.com"
# Webhook
webhook.mode = "environment"
zendesk = { mode = "environment" }
screener = { mode = "s3" }
allow_test_accounts_with_mainnet_keysets = true
monitored_electrum_nodes = [
    { network = "bitcoin", provider = "mempool", uri = "ssl://bitkey.va1.mempool.space:50002" },
    { network = "bitcoin", provider = "mempool", uri = "ssl://bitkey.fra.mempool.space:50002" },
    { network = "bitcoin", provider = "mempool", uri = "ssl://bitkey.tk7.mempool.space:50002" },
    { network = "bitcoin", provider = "blockstream", uri = "tcp://35.192.20.52:50001" },
    { network = "bitcoin", provider = "blockstream", uri = "tcp://34.147.244.49:50001" },
    { network = "bitcoin", provider = "blockstream", uri = "tcp://34.131.144.107:50001" },
]
kms = "environment"
