[package]
edition = { workspace = true }
links = "teltra"
name = "teltra-sys"
publish = { workspace = true }
version = { workspace = true }

[build-dependencies]
bindgen = "0.72.0"
make-cmd = "0.1.0"
