FROM amazonlinux:2@sha256:90e48c53055fc5943819e6a75e0227ecd43384ba3dbe949030f164645c485518 as nitro-cli
RUN amazon-linux-extras install -y aws-nitro-enclaves-cli docker \
    && yum install -y tar
# The nitro-cli needs its /blobs sources available under /usr/share/nitro_enclaves/blobs to build enclave images
RUN curl -L -o nitro-cli.tar.gz https://github.com/aws/aws-nitro-enclaves-cli/archive/refs/tags/v$(nitro-cli --version | awk '{print $NF}').tar.gz \
    && mkdir -p nitro-cli \
    && tar -C nitro-cli --strip-components=1 -xzf nitro-cli.tar.gz \
    && mkdir -p /usr/share/nitro_enclaves \
    && cp -r nitro-cli/blobs/`arch` /usr/share/nitro_enclaves/blobs \
    && rm -rf nitro-cli*
