[package]
edition = "2021"
name = "auth_lambda_handlers"
publish = false
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "create_auth_challenge"

[[bin]]
name = "define_auth_challenge"

[[bin]]
name = "verify_auth_challenge"

[[bin]]
name = "pre_token_generation"

[dependencies]
aws_lambda_events = "0.15.0"
serde_json = "1.0.114"
tokio = { version = "1.36.0", features = ["full"] }
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
# NOTE: the following crate is not part of the SDK, but it is maintained by AWS.
base64 = "0.22.0"
lambda_runtime = "0.13.0"
rand = "0.8.5"
secp256k1 = { version = "0.28.2", features = ["hashes", "serde"] }

#[dev-dependencies]
bitcoin_hashes = "0.13.0"
