[package]
edition = { workspace = true }
name = "wsm-api"
publish.workspace = true
version = "0.1.0"

[[bin]]
name = "wsm-api"

[dependencies]
anyhow = { workspace = true }
aws-config = { workspace = true }
aws-credential-types = { workspace = true }
aws-sdk-dynamodb = { workspace = true }
aws-sdk-kms = { workspace = true }
aws-types = { workspace = true }
axum = { workspace = true, features = ["json", "macros"] }
axum-macros = { workspace = true }
axum-tracing-opentelemetry = { workspace = true }
base64 = { workspace = true }
config = { workspace = true, features = ["toml"] }
crypto = { workspace = true }
log = "0.4.21"
reqwest = { workspace = true, default-features = false, features = [
  "json",
  "rustls-tls",
] }
serde = { workspace = true }
serde_dynamo = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }
ulid = { workspace = true }

# path dependencies
wallet-telemetry = { workspace = true }
wsm-common = { workspace = true }

[lints]
workspace = true
