#!/usr/bin/env bash

set -euo pipefail

echo "Activate Hermit"
source bin/activate-hermit

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
"$SCRIPT_DIR"/EnsureGitLFS

app/ios/Scripts/CI/FetchBuildVariables "$1"

echo "Building Xcode Project"
REPRODUCIBLE_BUILD="$(pwd)/reproducible-build-variables.json" just app/xcodegen
