#!/usr/bin/env bash

set -euo pipefail

echo "Hermit clean"
source bin/activate-hermit
hermit clean --packages
hermit update

echo "Building Xcode Project"
gradle --project-dir=app :shared:app-component-impl:kspKotlinIosSimulatorArm64 --rerun
just app/xcodegen
