#!/usr/bin/env bash

set -euo pipefail

echo "Activate Hermit"
source bin/activate-hermit

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
"$SCRIPT_DIR"/EnsureGitLFS

source bin/activate-hermit

echo "Run KMP iOS Tests... "
gradle --project-dir=app detektIosArm64Main detektIosArm64Test
