/**
 * @file metadata.h
 * @brief POSIX implementation of metadata.h (intentionally NOT a passthrough).
 *
 * On hardware, metadata lives in dedicated flash pages written at build/
 * provisioning time; lib/metadata parses them. In the simulator those pages
 * are zero-filled RAM (see task_stubs.c), so the real metadata_get* would
 * report METADATA_INVALID and device_info would fail. There is no C writer
 * for the metadata wire format (it is generated by build tooling), and the
 * real metadata.o is pulled into the link by lib/fwup, so the functions
 * cannot be overridden in a core-sim object without duplicate symbols.
 * Instead, these static-inline placeholders shadow the library for sources
 * compiled against this header.
 *
 * Keep the types in sync with lib/metadata/inc/metadata.h — they are
 * type-checked only here.
 */

#pragma once

#include "attributes.h"
#include "wallet.pb.h"

#include <stdbool.h>
#include <stdint.h>
#include <string.h>

#define METADATA_BUILD_STR_MAX_LEN  7
#define METADATA_GIT_STR_MAX_LEN    64
#define METADATA_HW_REV_STR_MAX_LEN 32
#define METADATA_HASH_LENGTH        20

#ifndef CORE_SIM_HW_REVISION
#define CORE_SIM_HW_REVISION "w1a-evt"
#endif

typedef enum {
  META_TGT_BL,
  META_TGT_APP_A,
  META_TGT_APP_B,
  META_TGT_MAX,
} metadata_target_t;

typedef struct {
  metadata_target_t target;
  struct {
    char id[METADATA_GIT_STR_MAX_LEN + 1];
    char branch[METADATA_GIT_STR_MAX_LEN + 1];
  } git;
  struct {
    uint8_t major;
    uint8_t minor;
    uint8_t patch;
  } version;
  char build[METADATA_BUILD_STR_MAX_LEN + 1];
  uint64_t timestamp;
  uint8_t sha1hash[METADATA_HASH_LENGTH];
  char hardware_revision[METADATA_HW_REV_STR_MAX_LEN];
} metadata_t;

typedef enum {
  METADATA_VALID,
  METADATA_INVALID,
  METADATA_MISSING,
  METADATA_ROOT_ERROR,
} metadata_result_t;

// posix_active_slot is defined via assembly with address value 1 (SLOT_A)
extern char posix_active_slot[];

static inline metadata_result_t metadata_get(metadata_target_t target, metadata_t* meta) {
  if (!meta)
    return METADATA_INVALID;

  memset(meta, 0, sizeof(*meta));
  meta->target = target;
  meta->version.major = 1;
  strncpy(meta->git.id, "posix-emulator-stub", METADATA_GIT_STR_MAX_LEN);
  strncpy(meta->git.branch, "core-sim", METADATA_GIT_STR_MAX_LEN);
  strncpy(meta->build, "posix", METADATA_BUILD_STR_MAX_LEN);
  strncpy(meta->hardware_revision, CORE_SIM_HW_REVISION, METADATA_HW_REV_STR_MAX_LEN);
  return METADATA_VALID;
}

static inline metadata_result_t metadata_validity(metadata_target_t UNUSED(target)) {
  return METADATA_VALID;
}

static inline metadata_result_t metadata_get_active_slot(metadata_t* meta,
                                                         fwpb_firmware_slot* slot) {
  if (slot)
    *slot = fwpb_firmware_slot_SLOT_A;
  return metadata_get(META_TGT_APP_A, meta);
}

static inline metadata_result_t metadata_get_firmware_version(uint32_t* version) {
  if (version)
    *version = (1 << 16);
  return METADATA_VALID;
}

static inline void metadata_print(metadata_target_t UNUSED(target)) {}
