#!/usr/bin/env python3
"""Generate authentication check code for core-sim from IPC YAML files.

This script reads the same YAML files used by the real firmware's IPC codegen
and generates a header with auth requirements for the core-sim emulator.

Auth levels (from real firmware):
  never           - No auth required
  always          - Always requires authentication
  after_onboarding - Requires auth only if device is onboarded
  before_onboarding - Requires device to be not onboarded
"""

import glob
import os
import sys

try:
    import yaml
except ImportError:
    print("Error: PyYAML not installed. Run: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# firmware/ root is 3 levels up from this script (scripts -> core-sim -> app
# -> firmware). Globbing wider than the firmware source tree is dangerous:
# stale checkouts/worktrees with old IPC YAMLs would leak protos into the
# generated header.
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
FIRMWARE_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(SCRIPT_DIR)))


def collect_yaml_files():
    """Find all IPC YAML definition files in the firmware source tree."""
    files = []
    for subdir in ("app", "lib"):
        pattern = os.path.join(FIRMWARE_ROOT, subdir, "**", "*_ipc.yaml")
        files.extend(glob.glob(pattern, recursive=True))
    return sorted(files)


def parse_auth_requirements():
    """Parse YAML files and return protos by auth level."""
    auth_after_onboarding = []
    auth_before_onboarding = []
    auth_always = []

    for file in collect_yaml_files():
        with open(file) as f:
            defn = yaml.safe_load(f)
            if "messages" not in defn or "protos" not in defn["messages"]:
                continue
            for proto in defn["messages"]["protos"]:
                name = proto["name"]
                auth = proto.get("auth", "never")
                # Convert fwpb_wipe_state_cmd -> fwpb_wallet_cmd_wipe_state_cmd_tag
                tag_name = name.replace("fwpb_", "fwpb_wallet_cmd_") + "_tag"
                if auth == "after_onboarding":
                    auth_after_onboarding.append(tag_name)
                elif auth == "before_onboarding":
                    auth_before_onboarding.append(tag_name)
                elif auth == "always":
                    auth_always.append(tag_name)

    return (
        sorted(set(auth_after_onboarding)),
        sorted(set(auth_before_onboarding)),
        sorted(set(auth_always)),
    )


def generate_header(auth_after_onboarding, auth_before_onboarding, auth_always):
    """Generate C header with auth check matching real firmware logic."""
    after_onboarding_cases = "\n".join(f"    case {tag}:" for tag in auth_after_onboarding)
    before_onboarding_cases = "\n".join(f"    case {tag}:" for tag in auth_before_onboarding)
    always_cases = "\n".join(f"    case {tag}:" for tag in auth_always)

    # Handle empty always cases
    if always_cases:
        always_block = f"""{always_cases}
      return is_authenticated;"""
    else:
        always_block = "    // (none currently defined)"

    return f'''/**
 * @file stdio_auth_check.h
 * @brief Auto-generated authentication requirements from IPC YAML files
 *
 * DO NOT EDIT - Generated by scripts/gen_auth_check.py
 * Source: firmware/app/tasks/ *_ipc.yaml files
 *
 * Auth levels (from real firmware):
 *   never            - No auth required
 *   always           - Always requires authentication
 *   after_onboarding - Requires auth only if device is onboarded
 *   before_onboarding - Requires device to be not onboarded
 */

#ifndef STDIO_AUTH_CHECK_H
#define STDIO_AUTH_CHECK_H

#include "wallet.pb.h"

#include <stdbool.h>
#include <stdint.h>

/**
 * Check if command requires authentication.
 * Mirrors real firmware logic from ipc_internal.jinja.c:check_authentication()
 *
 * @param tag Proto command tag
 * @param is_onboarded Whether device has completed onboarding
 * @param is_authenticated Whether user is authenticated (unlocked)
 * @return true if command is allowed, false if UNAUTHENTICATED should be returned
 */
static inline bool stdio_check_auth(uint32_t tag, bool is_onboarded, bool is_authenticated) {{
  // Commands that always require auth (auth: always)
  switch (tag) {{
{always_block}
    default:
      break;
  }}

  // Commands that require auth only after onboarding (auth: after_onboarding)
  switch (tag) {{
{after_onboarding_cases}
      if (!is_onboarded) {{
        return true;  // Not onboarded yet - allow without auth
      }}
      return is_authenticated;  // Onboarded - require auth
    default:
      break;
  }}

  // Commands that are allowed only before onboarding (auth: before_onboarding)
  switch (tag) {{
{before_onboarding_cases}
      return !is_onboarded;
    default:
      break;
  }}

  // All other commands (auth: never) - no auth required
  return true;
}}

#endif /* STDIO_AUTH_CHECK_H */
'''


def main():
    auth_after_onboarding, auth_before_onboarding, auth_always = parse_auth_requirements()

    print(f"Found {len(auth_after_onboarding)} protos with auth: after_onboarding")
    print(f"Found {len(auth_before_onboarding)} protos with auth: before_onboarding")
    print(f"Found {len(auth_always)} protos with auth: always")

    header = generate_header(auth_after_onboarding, auth_before_onboarding, auth_always)

    output_dir = os.environ.get(
        "CORE_SIM_AUTH_CHECK_OUT_DIR",
        os.path.join(SCRIPT_DIR, "..", "src", "generated"),
    )
    os.makedirs(output_dir, exist_ok=True)
    output_file = os.path.join(output_dir, "stdio_auth_check.h")

    with open(output_file, "w") as f:
        f.write(header)

    print(f"Generated {output_file}")


if __name__ == "__main__":
    main()
